### ISSUE TITLE
[🚀 Feature]: Reduce the difficulty and amount of code required for using Selenium.

### ISSUE THREAD

**Issue by iamxiaojianzheng** [SeleniumHQ/seleniumhq.github.io#1338]
### Feature and motivation

I have read the documentation for Playwright, and ignoring their respective features, in terms of ease of use, I think Playwright seems more convenient and considers more aspects. I don't know why Selenium has not made any breakthroughs in code usability. As a Selenium user, I hope that SeleniumHQ can take action in this area.

```java
WebDriver driver = new ChromeDriver();
driver.get("https://google.com/ncr");
driver.findElement(By.name("q")).sendKeys("cheese" + Keys.ENTER);
// Initialize and wait till element(link) became clickable - timeout in 10 seconds
WebElement firstResult = new WebDriverWait(driver, Duration.ofSeconds(10))
        .until(ExpectedConditions.elementToBeClickable(By.xpath("//a/h3")));
// Print the first result
System.out.println(firstResult.getText());
```

Code like this is inadvisable in my opinion. It would be even better if it could be as simple as the following code.

```java
WebDriver driver = new ChromeDriver();
WebElement firstResult = driver.get("https://google.com/ncr")
    .input(By.name("q"), "cheese" + Keys.ENTER)
    .untilWait(ExpectedConditions.elementToBeClickable(By.xpath("//a/h3")));
// Print the first result
System.out.println(firstResult.getText());
```

Input or click and other similar operations should provide a default waiting mechanism instead of allowing users to implement them one by one. 

Selenium can provide customized interfaces to allow users to make more detailed adjustments, but there should be a general waiting mechanism to Handles all basic operations.

Maybe there's something I haven't considered, but all in all, I hope selenium is getting better and better.

**Comment by diemol** [comment]
We are progressively starting to promote frameworks built on top of Selenium that address your point. All from the ecosystem https://www.selenium.dev/ecosystem/#frameworks. One of them for Java is Selenide, https://selenide.org/quick-start.html, it does what you are asking for.

**Comment by diemol** [comment]
You can reach out to their project.

**Comment by titusfortner** [comment]
This is a great issue because it surfaces a significant concern a lot of people have with Selenium right now. 

There are a bunch of different ways you can choose to locate/cache/wait for elements. Any choice Selenium makes here that would help users (and it *would help users), would also prevent other people from choosing a different strategy that makes more sense for them. 

Selenium's primary purpose is to provide the most accurate cross-browser way to automate browser interactions. We try to follow the Unix Philosophy of "do one thing and do it well," and that means that everything more than communication with the browser via the driver is outside the scope of the project at this time.
