### ISSUE TITLE
[🐛 Bug]: Getting Started - Installing Browsers

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/seleniumhq.github.io#1420]
### What happened?

The getting started section should be explicit that you have to install the browsers as well as the library. I guess put it on library install page?

### What browsers and operating systems are you seeing the problem on?

n/a

**Comment by eaccmk** [comment]
I see this in the docs @titusfortner , do you think your bug is still valid ?
https://www.selenium.dev/documentation/webdriver/getting_started/

<img width="1268" alt="Screenshot 2023-09-01 at 9 57 58 PM" src="https://github.com/SeleniumHQ/seleniumhq.github.io/assets/19251569/12cf7f35-5fac-4d70-917c-c090ff04a9ef">

**Comment by titusfortner** [comment]
It could have been more explicit. The real reason this is no longer am issue is that Selenium auto downloads browsers now as well.
