### ISSUE TITLE
Simple mistake in docs choice of phrase in French

### ISSUE THREAD

**Issue by griswolf** [SeleniumHQ/seleniumhq.github.io#526]
## 🐛 Bug Report
At this url: https://www.selenium.dev/documentation/en/introduction/the_selenium_project_and_tools/

You say "into the du jour remote control library for user agents"
"du jour" means "of the day" it is commonly found on restaurant menus to describe the soup du jour and similar things. It does NOT mean "by law" which in Latin is usually expressed as "de jure" usually contrasted with "de facto" "as things really are". I think you want one of the latin phrases.

## To Reproduce
This is a document mistake. Visit the URL mentioned above. There it is.

## Expected behavior
I expect that documentation will be literate and correct

## Environment
Documentation. My environment is irrelevant

**Comment by diemol** [comment]
Thank you for raising this up, @griswolf!

Would you like to contribute and help us improve the text?
[Here](https://www.selenium.dev/documentation/en/contributing/) is a detailed guide that shows how to do it.

**Comment by SixPMFriday** [comment]
I thought the wording (wordplay?) was excellent and I hope you keep it, @diemol! 

"The du jour remote control library for user agents" is a novel turn-of-phrase which actually does present the Selenium WebDriver API as the current day de facto / standard, while tastefully acknowledging the inevitability of future changes.

Reading the documentation at face value, it's reasonable to interpret the "du jour" bon mot as "this day", rather than "of the day" (as in soup du jour). So the phrase reads something like: "the current-day remote control library for user agents."

I agree with @griswolf that the use of "du jour" feels dissonant at first -- the phrase carries a contradicting connotation. The most common translation for this bon mot ("of the day") suggests something transient, while a standard is supposed to be relatively permanent!

However, standards, much like Selenium, do change, and so especially given the context of the documentation (a discussion of the history of Selenium, which includes many changes), using "du jour" this way seems like a clever way to add nuance IMO. 

It feels like a nod to the value of learning Selenium in its current state, 
and a wink at the fact that change is inevitable.

**Comment by diemol** [comment]
Thanks for your input, @SixPMFriday! 

I believe there is not much for us to do here since there are different opinions, but more importantly, no PR was sent (or an intention of it).

Closing this for now.
