### ISSUE TITLE
Documentation on how to invoke user script

### ISSUE THREAD

**Issue by tomas-eklund** [SeleniumHQ/seleniumhq.github.io#725]
## 🚀 Feature Proposal for the site or the documentation

People new to the Selenium world would probably benefit greatly from a step-by-step, super simple, getting started "Hello world" tutorial. How to install the necessary components, writing your first script and _how to execute it_.

## Motivation

I had to port a simple web scraping solution from PhantomJS/CasperJS to Selenium and I read through most of the pages on https://www.selenium.dev/documentation/, but the content was insufficient to get me started. The one thing that stumped me was: how in the world do I invoke my script (Javascript)? With CasperJS you invoke the casperjs.exe executable with your script as a command line parameter. 

`C:\> casperjs myscript.js`

Only after countless hours of Googling and watching Youtube Selenium tutorials (most of which uses Java or Python - which was of no help to me) did I realize that I should run it through Node.js. 

`C:\> nodejs myscript.js`

My problem is probably that I haven't used Node.js before. But had there been a better onboarding guide, I would probably have been up and running within an hour instead of feeling (being) stupid for several days.

**Comment by diemol** [comment]
We revamped the getting started pages, but we do not go all the way to the level of giving specific instructions on how to run a script because there are many different ways to do that depending on the language, and Selenium itself is not a single binary like the example you mention. That is why we consider this as done.

https://www.selenium.dev/documentation/webdriver/getting_started/
