### ISSUE TITLE
Relative Locator > near () distance python 

### ISSUE THREAD

**Issue by allenabc** [SeleniumHQ/seleniumhq.github.io#731]
## 🐛 Bug Report

Did you find something wrong with the site or the documentation? Please describe
your finding in a clear and concise way. 

## To Reproduce

How can we reproduce the issue you found? Please tell us how we can do that. 
Don't forget to add:

* Absolute link where the issue was found
* Screenshot (if needed) 
* The environment you had when the issue was found (see below)

Tell us the detailed steps to reproduce it:

## Expected behavior

What do you expected to happen? How should have it worked?

## Environment

* OS: 
* Browser: 
* Browser version: 

Would like to specify distance rather than using the default of 50 pixels. I tried a number of ways to enter an int value in python

1. Would like to enter an int value in python 
2. Would suggest adding this to the documentation for all languages

**Comment by diemol** [comment]
💬 It looks like this is a question rather than an issue.
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
