### ISSUE TITLE
How to set a browser on the top of the desktop?

### ISSUE THREAD

**Issue by kevin1101** [SeleniumHQ/seleniumhq.github.io#765]
## 💬 Questions and Help

I opened four browsers 
when i check the first one and do some test
i used `this.driver.manage().window().fullscreen();` at the first 
but other windows always cover on the top of the first window in the testing
so ,
i want to know how to set a browser on the top of the desktop.

**Comment by diemol** [comment]
💬 It looks like this is a question rather than an issue.
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
