### ISSUE TITLE
[🚀 Feature]: Explain how to import the driver in JS

### ISSUE THREAD

**Issue by kuba-orlik** [SeleniumHQ/seleniumhq.github.io#953]
### Feature and motivation

While reading the driver guide, it recommends the following code: 

```js
  let options = new firefox.Options();
  let driver = await new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build();

  await driver.quit();
```

But id doesn't say how to import the `firefox` and `Builder` objects.

**Comment by harsha509** [comment]
HI @kuba-orlik ,

We have precise documentation on how to use Firefox capabilities in [here](https://www.selenium.dev/documentation/webdriver/capabilities/firefox/#define-capabilities-using-firefoxoptions), along with imports for the reference.

If possible, could you please provide me the link where the above code is taken reference from ? so that we can take a look and fix it if necessary!

Thanks,
Harsha

**Comment by kuba-orlik** [comment]
I'm talking about this page:

https://www.selenium.dev/documentation/webdriver/getting_started/open_browser/#firefox

It was the first page I encountered when diving into exploring Selenium and it left me a little bit confused! ;)
